# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sysiphux/workspace/university/asm/video_merger

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sysiphux/workspace/university/asm/video_merger

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sysiphux/workspace/university/asm/video_merger/CMakeFiles /home/sysiphux/workspace/university/asm/video_merger//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sysiphux/workspace/university/asm/video_merger/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named merge_64

# Build rule for target.
merge_64: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 merge_64
.PHONY : merge_64

# fast build rule for target.
merge_64/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_64.dir/build.make CMakeFiles/merge_64.dir/build
.PHONY : merge_64/fast

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_64.dir/build.make CMakeFiles/merge_64.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_64.dir/build.make CMakeFiles/merge_64.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_64.dir/build.make CMakeFiles/merge_64.dir/main.c.s
.PHONY : main.c.s

merge.o: merge.c.o
.PHONY : merge.o

# target to build an object file
merge.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_64.dir/build.make CMakeFiles/merge_64.dir/merge.c.o
.PHONY : merge.c.o

merge.i: merge.c.i
.PHONY : merge.i

# target to preprocess a source file
merge.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_64.dir/build.make CMakeFiles/merge_64.dir/merge.c.i
.PHONY : merge.c.i

merge.s: merge.c.s
.PHONY : merge.s

# target to generate assembly for a file
merge.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_64.dir/build.make CMakeFiles/merge_64.dir/merge.c.s
.PHONY : merge.c.s

merge_asm_64.o: merge_asm_64.asm.o
.PHONY : merge_asm_64.o

# target to build an object file
merge_asm_64.asm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_64.dir/build.make CMakeFiles/merge_64.dir/merge_asm_64.asm.o
.PHONY : merge_asm_64.asm.o

merge_opt.o: merge_opt.c.o
.PHONY : merge_opt.o

# target to build an object file
merge_opt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_64.dir/build.make CMakeFiles/merge_64.dir/merge_opt.c.o
.PHONY : merge_opt.c.o

merge_opt.i: merge_opt.c.i
.PHONY : merge_opt.i

# target to preprocess a source file
merge_opt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_64.dir/build.make CMakeFiles/merge_64.dir/merge_opt.c.i
.PHONY : merge_opt.c.i

merge_opt.s: merge_opt.c.s
.PHONY : merge_opt.s

# target to generate assembly for a file
merge_opt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_64.dir/build.make CMakeFiles/merge_64.dir/merge_opt.c.s
.PHONY : merge_opt.c.s

merge_simd_64.o: merge_simd_64.asm.o
.PHONY : merge_simd_64.o

# target to build an object file
merge_simd_64.asm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_64.dir/build.make CMakeFiles/merge_64.dir/merge_simd_64.asm.o
.PHONY : merge_simd_64.asm.o

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... merge_64"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... merge.o"
	@echo "... merge.i"
	@echo "... merge.s"
	@echo "... merge_asm_64.o"
	@echo "... merge_opt.o"
	@echo "... merge_opt.i"
	@echo "... merge_opt.s"
	@echo "... merge_simd_64.o"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

